### ISSUE TITLE
Add autosave function to the various goal creation and editing screens

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#780] opened 2022-09-13 18:39 UTC
Applying the same logic that was recently added to the open conversations page, let's add the 15 minute auto-save function to:

My Goals > Create New Goal
My Goals > Edit Goal

For Supervisor:
My Goals > Goal Bank > Add Goal to Bank
My Goals > Goal Bank > Edit Goal in Goal Bank

**Comment by steffipravasi** [comment] 2022-11-29 01:21
**Test status: Fail**
1) Create new goal - The autosave function when the same tab is open occurs in 4 minutes only. Expected: Auto save must occur after 15 mins
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Test%20cases/AutoSaveOccursIn4mins.mov?csf=1&web=1&e=8SxnD2

2) Create new goal: When new goal details are added and user navigated to other tab, the auto save function occurs but user is not notified
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Test%20cases/AutoSaveUserNotNotified.mov?csf=1&web=1&e=2bQLnS

**Comment by jizhaogit** [comment] 2022-11-29 19:14
Hi @steffipravasi , all the comments js trigger time is confirmed to set as 15 minutes.   the auto save function also be changes not to use the submit button but replaced by a new ajax save call to avoid page auto-reloading and notification message removing.

**Comment by jizhaogit** [comment] 2022-11-29 19:29
once the time tracking improved to track modal behavior will apply the same fix in goal auto save time tracking.

**Comment by steffipravasi** [comment] 2022-11-30 10:21
Env: Test
The auto save function for Goals is working fine after 15 mins.
Appears in: 
- Create new goal
- Edit goal
- Add goal to goal bank
- Edit goal to goal bank
The functioning might change a little bit if the changed sections after auto saving are decided to be highlighted.

**Comment by jizhaogit** [comment] 2022-12-02 19:59
step by step for goal title and tag selection is applied as request.

**Comment by Travis-A-Clark** [comment] 2022-12-06 17:55
@jizhaogit Is it possible to add a pop-up if someone tries to click in the comments boxes before they filled out the top section that explains what's happening? Like: "Please fill out the goal type, title, and tags before adding the description."

**Comment by SSubashree26** [comment] 2022-12-12 21:56
Following are the observations that were found during validating this story 
1 -> If there is an error message displayed during the goal creation, the auto save popup is not at all displayed after that
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23%20780/Error%20message%20-%20while%20autosaving.mov?csf=1&web=1&e=sUvcga

2-> For Supervisor - adding a goal in goal bank is not showing the autosave message
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23%20780/Supervisor%20-%20Goal%20Bank%20-%20Add%20goal%20to%20bank%20-%20did%20not%20work%202.mov?csf=1&web=1&e=4zwclR

3->In Firefox, after the autosave popup is displayed, the goal gets closed. We will have to open it again incase if we had to type some more details
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23%20780/FF%20-%20Autosave%20-%20ok%20-%20closes%20the%20goal%20window.mov?csf=1&web=1&e=bCO5O3

4-> Performed the following 
- Started creating a goal 
- if there is an error while creating the goal, the autosave message is not displayed
- then I cancelled creating the goal 
- then tried to open a new goal and filled in all the details
- when it was time for autosave message to show, error message is displayed even if there are no errors in the screen right now
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23%20780/Error%20message%20-%20while%20autosaving.mov?csf=1&web=1&e=sUvcga

5 -> there is no "comments saved" kind of text displayed when we click ok in the autosave button

6 -> the text in the autosave message needs to be changed. It has to be "your goal has been" instead of "your goal have been" which is a grammatical error
![image.png](https://images.zenhubusercontent.com/63892df90d58261296a2b5c0/00f76dc4-233e-4e11-aa65-a2575b2ca84e)

Ji had a look at the observations and provided the following feedback
1. goal auto-save is just not rolled playing if a warning message popup. thats for warning people they have some error need to take care of
2. need to check js code to fixing
3. need to check js code to fixing
4. need to check js code to fixing
5. based on the design and requirements, we want the goal description field to be warned and autosaved.  once this one be saved the form can be submitted.  no need to add "comment save" notify for my opinion but we can talk it later
6. will change soon when I loop back to the goal items

Based on the comments above, Ji might have to look into it further. Therefore moving it back to "In progress" column

**Comment by SSubashree26** [comment] 2022-12-22 21:51
@jizhaogit 

I am still able to recreate the observation 1, in which, after an error message is displayed the autosave message is not at all displayed 

Also I noticed that there are two goals being created while performing the following
- Navigate to My goal > My current goals > Create New Goal
- Fill in all the details for the new goal and do not click on the "Save Changes" button
- Leave the screen until the autosave message is displayed 
- Click on "Ok" button in the autosave message. "Your goal has been saved" message is displayed, however, no goal is created in the goals list as we did not click on the "Save Changes" button
- Close the goal without saving the changes 
- Create a new goal and click on "Save Changes" button
- There are two goals created ( 1 - which was saved but discarded initially and 2 - which was saved and completed)
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23%20780/Two%20goals%20are%20created%20.mov?csf=1&web=1&e=nQC5Xl

**Comment by jizhaogit** [comment] 2023-01-03 17:32
a new fix is applied for item 1.

**Comment by SSubashree26** [comment] 2023-01-05 16:14
@jizhaogit for item 1, the autosave message is displayed once. However, post that, the autosave message is not displayed at all. Can you please have a look at it?
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23%20780/780%20-%20Validation%20on%2005%20Jan%202023.mov?csf=1&web=1&e=OVEuAk

**Comment by SSubashree26** [comment] 2023-01-23 22:24
@jizhaogit  Hi Ji, the error messages are disappearing this time. However, the autosave message is not displayed for the second time, when an error was displayed already and corrected.

https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%20%23%20893/Performance%20%23893%20-%20Part%202.mov?csf=1&web=1&e=rE1Ike

**Comment by jizhaogit** [comment] 2023-01-25 15:24
@SSubashree26 for some reason i cannot access your movie. Can we have a chat to talk about this issue? because i tried both in my local and test enviorment but cannot reproduce your issue.  thanks

**Comment by SSubashree26** [comment] 2023-01-25 17:13
@jizhaogit I have uploaded the file again. https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23%20780/780%20-%2023%20Jan%2023.mov?csf=1&web=1&e=Fpws0L

**Comment by SSubashree26** [comment] 2023-01-25 22:00
@jizhaogit While editing a goal, the auto save message is displayed more than once. Can you please have a look at it?

https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23%20780/Editing%20a%20goal%20-%20auto%20save%20is%20displayed%20twice.mov?csf=1&web=1&e=vCm7bv

**Comment by SSubashree26** [comment] 2023-01-25 22:00
@jizhaogit While editing a goal, the auto save message is displayed more than once. Can you please have a look at it?

https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23%20780/Editing%20a%20goal%20-%20auto%20save%20is%20displayed%20twice.mov?csf=1&web=1&e=vCm7bv

**Comment by jizhaogit** [comment] 2023-01-26 18:01
@telusdcinco Please review the code changes.  thanks

**Comment by SSubashree26** [comment] 2023-02-09 19:01
Completed validating this story in the test environment and it is working fine. The autosave message is not displayed for the second time which is working as expected. Moving to PO review column

Screen Recording:
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%20%23865/Performance%20%23865.mov?csf=1&web=1&e=BzlyEQ

**Comment by Travis-A-Clark** [comment] 2023-02-10 21:15
@jizhaogit I don't think the Description field needs to be mandatory anymore. If someone has filled out the goal type, title and tags, then the description is enabled and the goal should be saved whether a description is added or not.

Apologies if this is a new requirement or if I wasn't clear before. I know we have worked on a few versions of this over the lsat few months!

**Comment by SSubashree26** [comment] 2023-02-15 18:03
@jizhaogit Observed that the auto save message is displayed incorrectly (sometimes after the "Add goal to Bank" modal is closed)

In the below recording, after the "Add goal to Bank" modal was cancelled and was reopened, the auto save message was displayed even before 15 minutes of inactivity ( less than 1 minute in the testing environment)

https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/Product%20Team/Testing/Testing%20screenshots/Performance%23%20780/Add%20goal%20bank%20-%20autosave%20message%20displayed%20incorrectly.mov?csf=1&web=1&e=ooDiLY

**Comment by jizhaogit** [comment] 2023-02-15 18:06
for the testing purpose ALL the goal autosave time roll is set to 1 minute.

**Comment by jizhaogit** [comment] 2023-02-15 18:06
we will modify it to 15 minutes when it is ready for deployment

**Comment by jizhaogit** [comment] 2023-02-15 18:17
Added a various to force the time roll counting always get refreshed when close the goal modal window.

**Comment by jizhaogit** [comment] 2023-02-15 18:55
modified the goal related autosave time from 1 minute to 15 minutes.

**Closed** 2023-02-17 18:03 UTC
Labels: enhancement, PO Approved
