### ISSUE TITLE
Create "Service Representative" role and permissions

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#942] opened 2023-04-05 16:38 UTC
**Current Situation**

We have roles for: employee, supervisor, HR Admin (by business unit), Sys Admin (for all employees)

**Desired Outcome**

- Create a new role: Service Representative
- Add functions: Employee List, Switch Identity
- This is for all employees (like Sys Admin)
- Add this option to the Sys Admin > Access and Permissions page to add/edit this role

**Comment by jizhaogit** [comment] 2023-06-21 18:29
@Travis-A-Clark 
All the requests are done. But have a question about the switch process:

User A is a member of role "Service Prepresentative" ONLY.  And currently system allows him to switch identity to a system admin account and can get the permissions of system admin.  Would that be the expect behaviors or do we need to block this account switching? Please advise.

**Comment by Travis-A-Clark** [comment] 2023-06-21 20:01
@jizhaogit Good question! I think the Service Representative access should only be able to view Home, My Goals, My Conversations, and My Team. Not HR or Sys Admin. Thank you!

**Comment by jizhaogit** [comment] 2023-06-23 13:29
ready for testing

**Comment by jizhaogit** [comment] 2023-06-23 13:29
ready for testing

**Comment by steffipravasi** [comment] 2023-06-26 13:58
1) The Org drop down list for Service Rep does not display results for all pages
![Screenshot 2023-06-26 at 9.56.19 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/b5afc1ee-a4fd-4b8e-a0ba-73b17a303921)

**Comment by telusdcinco** [comment] 2023-06-27 01:08
@steffipravasi 
Fix implemented to address security changes allowing dropdown to be populated with orgs similar to SysAdmin access.

**Comment by steffipravasi** [comment] 2023-06-27 15:48
@Travis-A-Clark For a SR role profile, should the functions like Employee List, Switch Identity be displayed under the name of tab Sys Administration or Service Representative?

**Comment by steffipravasi** [comment] 2023-06-27 17:03
@telusdcinco Can we please change the name of the tab to Service Representative.

**Comment by telusdcinco** [comment] 2023-06-27 17:27
Left panel menu label changes to Service Representative.

Pushing change to Test.

**Comment by Travis-A-Clark** [comment] 2023-06-27 20:07
@telusdcinco @steffipravasi we have our first training session with Service Reps on Thursday (June 29). We will definitely need this up and running in our training environment before then.

**Comment by steffipravasi** [comment] 2023-06-27 20:37
@telusdcinco SR can still see the entire menu for Hr and Sys admin when switching identity. 

Expected: Comment by Travis: I think the Service Representative access should only be able to view Home, My Goals, My Conversations, and My Team. Not HR or Sys Admin

**Comment by jizhaogit** [comment] 2023-06-27 21:40
SR account: May,Cathy
System admin account: Zilke,Karen

login as May,Cathy then switch identity to Zilke,Karen. the side bar is shown as the following:

![image.png](https://images.zenhubusercontent.com/620163b737f8d3386467e70d/d3a21d19-4151-4a32-a856-197312cc78ec)

right top login information:
![image.png](https://images.zenhubusercontent.com/620163b737f8d3386467e70d/fb7027f9-d0c4-4b12-9578-66654bd04052)

@steffipravasi 
Can you please provide the testing account you used?  thanks

**Comment by steffipravasi** [comment] 2023-06-27 21:44
@jizhaogit Accounts used are:
SR: 195168	Ruhl,Bonney
Switched account to: 000910	Shawna Wilson (HR admin) 
Also switched account to: 163102	Travis Clark ( HR and Sys admin)

**Comment by jizhaogit** [comment] 2023-06-27 22:01
have a short chat with @steffipravasi  and we found the issue is happened when login from functional user login form directly as a SR user. a new fix will deploy soon.

**Comment by jizhaogit** [comment] 2023-06-27 23:08
@steffipravasi the new fix is deployed.  please help verify. thanks!

**Comment by steffipravasi** [comment] 2023-06-28 14:42
Issue resolved and validated on test. SR role functionality works fine for login and switch identity. Ready for PO review.

**Comment by Travis-A-Clark** [comment] 2023-06-28 20:48
@steffipravasi Can you create a separate ticket to deal with this last issue around Sys Admin and SR navigation? If the SR function is working aside from that, I'd like to push it into Training as soon as possible. Thanks!

**Comment by steffipravasi** [comment] 2023-06-28 21:08
I had a chat with Ji this morning and he had confirmed to look at it in the afternoon. 
But yes the functionality is working fine now except for the issue raised in the last comment. Added it to a separate ticket #1014. Moving this ticket for PO review.

**Closed** 2023-08-17 16:22 UTC
Labels: user story, PO Approved
