### ISSUE TITLE
PDP Production Error Message

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#896] opened 2023-01-26 16:56 UTC
Production laravel.log showing the error message below.

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/2869ffb8-0380-4fca-8885-0d55b19e02a6)

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/c517c9bc-f665-4b73-af61-4b697f45682e)

**Comment by Travis-A-Clark** [comment] 2023-01-26 18:12
@jizhaogit Can you confirm that this error message has been addressed by the fix you mentioned this morning that is current in Test?

**Comment by jizhaogit** [comment] 2023-01-26 18:18
@Travis-A-Clark it is not the error message that i worked on with. what i fixed is the query error when login as sysadmin and open a conversation will get sql query error in dev/test environment. Verified production does not have that issue because we didn't push #889 yet.

**Comment by Travis-A-Clark** [comment] 2023-01-26 18:20
@telusdcinco Looks like this is a new issue that isn't being looked at currently. What is the impact of the error?

**Comment by telusdcinco** [comment] 2023-01-26 18:27
@Travis-A-Clark It is possible that the manager is getting an error message when clicking on the direct report in My Team.

**Comment by telusdcinco** [comment] 2023-09-08 16:30
[Uploading... image.png]

**Comment by telusdcinco** [comment] 2023-09-08 16:30
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ3VCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ae2ca8301944e10327425901a3595d791b6c95c6/image.png)

**Comment by steffipravasi** [comment] 2023-09-11 16:05
The issue is not observed on other environments so will need to verify it on prod after migration.
Moving to PO review.

**Closed** 2023-10-06 20:26 UTC
Labels: bug, question
