### ISSUE TITLE
Thread Count and Performance Throttling

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1204] opened 2024-01-17 00:03 UTC
Email from Jason Leach includes suggestion:

I noticed that the mySQL database is being throttled about 40% of the time. This can be for several reasons but after looking into the mySQL docs it appears it creates a thread for every connection. This may be problematic if you have several hundred simultaneous database connections. Each one of those threads may be fighting for CPU resources.

The solution, that worked well for the Health Gateway during vaccination pass issuance was not to add more CPU but to limit the maximum thread count. When they did this, the application performance greatly improved to what it is today.

I suggested to Warren that you trial a limit of the database connections by setting the option max_connections to something manageable like 16. Or, at least gather metrics on the number of connections and make sure this is not the root cause. Consider setting it at 5PM and monitoring for 1h. If that looks good then again monitor at 8AM and back out the changes if worse problems manifest. If not, leave the change for an observation period.

**Comment by warrenchristian1telus** [comment] 2024-01-18 17:03
For mysql pod, I have set max_connections=16 as recommended.

I was also able to adjust resourcing to allow for a bit more CPU allocation under load. 

We will continue to monitor for any changes to performance.

**Comment by Travis-A-Clark** [comment] 2024-01-25 22:00
Just a note that I put in the official request on the morning of Jan 24 to go from 4 CPU to 8 CPU in PROD (there was no option for 6). Dennis, Ji, and Jessica were copied on the email. Once the additional CPU have been confirmed, we should check response times and resource spikes in PROD again.

**Comment by Travis-A-Clark** [comment] 2024-01-31 22:45
The CPU increase was implemented on Jan 30

**Comment by telusdcinco** [comment] 2024-02-23 18:22
@warrenchristian1telus Is there additional changes required on infra side?

**Comment by Abuchana** [comment] 2024-02-23 18:24
@warrenchristian1telus can you check response times and resource spikes in PROD and confirm we are good to close this ticket?

**Comment by warrenchristian1telus** [comment] 2024-02-26 23:37
@telusdcinco @Abuchana Everything is looking pretty good to me. I have sent a couple of questions for the Dev Exchange team to verify things on their end, and clear-up some things to do with server stat monitoring / reporting for me, but it seems to be stable and handling the traffic well.

My thoughts now are that we may want to dial-down the CPU limit on the database server a bit to better match the requirement changes that came with the previous change (max_connections=16).

This would involve another small change and some (hopefully final) monitoring of performance to ensure that the resulting change is also stable. I believe we can reduce our server CPU limit "overhead" by roughly 50%, which should give us some room to implement the next round of changes, which will add redundancy to each service/pod (which will require additional request/limit resources).

We could likely close this now, as I believe the issue is technically resolved, but I wouldn't mind keeping it open until we get any final feedback/comments from Dev Exchange and ensure that everything is sized appropriately.

**Closed** 2024-03-07 22:52 UTC
Labels: enhancement, Priority
