### ISSUE TITLE
Start and End date in my Current goals displays 'Any' if start and date is selected together in any of these

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#933] opened 2023-03-29 18:14 UTC
The Start and End date fields in the Search fields for My Current Goals does not work together.
When user clicks on Start date, they can choose their start date and end date in the same Date picker. This results in displaying the start and end date in the Start date field itself. 
![Screenshot 2023-03-29 at 2.47.18 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/25fefb99-51fc-486e-afe7-aee63316b3b6)

The same issue occurs for end date: 
![Screenshot 2023-03-29 at 2.50.23 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/cd0dcfdf-759d-4297-bf1c-ec4e301c907d)

User can also enter two separate date timelines in start and end date
![Screenshot 2023-03-29 at 2.51.11 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/b3009b3f-a2ec-4ca5-9bcc-7c242180a804)

Expected results:
The start date and end date fields must work together but only let user select the particular date required for each field i.e start date only must be selected in start date field and end date must be selected from end date field

**Comment by Travis-A-Clark** [comment] 2023-07-15 20:23
This is behaving as intended. Start and end dates don't have to work together. For example, I could search for all goals that ended between Jan 1 and March 31 regardless of when I started them.

Closing ticket.

**Closed by Travis-A-Clark** 2023-07-15 20:23 UTC
Labels: bug
