### ISSUE TITLE
Conversation Due Dates are Incorrect (wrong year)

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1120] opened 2023-09-20 18:49 UTC
### Issue 1

Conversation being signed off on September 12, 2023 is generating next conversation due date of January 13, 2023 instead of January 13, 2024.

Example: Alexandra Hyde

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjI5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--23f1072c80b761d68256b6495c39891fcba65b53/image.png)

### Issue 2

Conversations being signed off by both parties on September 11, 2023 is not being recognized as complete. Next conversation due date still shows September 15, 2023. Overdue emails and notifications are being generated.

Example: Suyin Pan

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0crIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--19aa0ae6a2e363a3533d1549b8666e49cea30003/image.png)

**Comment by telusdcinco** [comment] 2023-09-20 20:46
Caused by the 2nd item fixed in #1033.

**Comment by telusdcinco** [comment] 2023-09-20 20:50
@jizhaogit  Please review fix for #1120.

**Comment by jizhaogit** [comment] 2023-09-20 20:52
looks good to me. thanks Dennis.

**Comment by telusdcinco** [comment] 2023-09-20 21:25
Next conversation due date calc process completed in Dev/Test.

**Closed** 2023-10-06 20:26 UTC
Labels: bug, PO Approved, Priority
