### ISSUE TITLE
Remove past employees from the statistics and reporting section

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#907] opened 2023-02-10 19:58 UTC
In ticket #888 Dennis removed past employees from the My Team view, and the HR/Sys Admin views for things like the Goal Bank and shared/excused employees.

However, past employees still show up in the statistics and reports page. 

For example, in TEST, employee ID 000778 Rosalind.Humphreys@gov.bc.ca, was moved to the past employees list on Feb 3 but she is still counted in the report for shared employees, excused employees, etc. in the Statistics and Reporting area. 

I know that Ji is working in the Stats and Reporting area now and that Dennis has done the work on past employees up until now. Not sure which of you is best suited to take on this ticket so please check with each other and then assign as needed. This is not for this sprint (Feb 8 - 22).

**Comment by steffipravasi** [comment] 2023-05-31 03:42
1) Home page -> My Profile is Shared with 
2) My Current Goals -> Shared with list
3) Conversations -> Participants list 
Past user: 000181	Ebata,Tim M
Account used to test issue 1,2,3 is Neil Bow (Neil's profile is currenty being shared with Tim)
4) My Team -> Share with list (Account used: Zeglen,Stefan)

**Comment by Travis-A-Clark** [comment] 2023-06-01 17:14
Please remove from all those places except #5 - Employee Record in Stats and Reporting.

**Comment by jizhaogit** [comment] 2023-06-05 15:54
@telusdcinco  Hi Dennis, please help do the code review. thanks!

**Comment by steffipravasi** [comment] 2023-06-06 23:31
Test fail
Test data: Past employee: Mortimer,Jeff D(Emp id:137586)
Team members: Struthers,Jordan can still see Jeff has his supervisor
1) Jordan can still see Jeff has his supervisor
As discussed in the meeting with Travis today, if the supervisor is no more an active employee, then we must roll back to the previous supervisor or to the supervisor a level higher for the Team member
Test data: Past employee: Mortimer,Jeff D(Emp id:137586)
Team members: Struthers,Jordan can still see Jeff has his supervisor
![Screenshot 2023-06-06 at 6.52.27 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/1c6bac49-b3c0-40d9-81c4-be53a4560e3d)
2) Jordan can still see Jeff in the participant list of conversation
![Screenshot 2023-06-06 at 6.53.29 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/5ae74f2c-c376-4763-8045-a39a2bcfe4d7)
3) Also in the Shared With List
![Screenshot 2023-06-06 at 6.54.49 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/9a9d155d-121c-4287-bb85-6890db5002fe)
Another Test data for the same issues as above: Past employee - 002197	Levitt,Steve, Team member - Meijer,Maarty

**Comment by jizhaogit** [comment] 2023-06-07 13:46
@steffipravasi 
mysql> select name, excused_flag from users where name = 'Jeff Mortimer';
+---------------+--------------+
| name          | excused_flag |
+---------------+--------------+
| Jeff Mortimer |            0 |
+---------------+--------------+
1 row in set (0.02 sec)

i found that the Jeff is not marked as excused user in the database.  We need to check what is "past employee" should be.  looks like the excused flag is not updated in this case (or this case is not for excusing?)

**Comment by Travis-A-Clark** [comment] 2023-06-07 17:00
@jizhaogit @steffipravasi Excused employees and past employees are not the same thing. Past employees have a date deleted value in their PeopleSoft record. Excused employees are still in PeopleSoft but may be on leave or long term disability, etc.

The criteria used to remove past employees from stats and reports should be the same as the logic used by Dennis to build out the Sys Admin > Employee List > Past Employees.

I thought that Dennis already took care of removing past employees from other parts of the platform (the conversation drop down list, etc). If they are showing up there again, that is a problem. I will find the ticket # for that work.

**Comment by Travis-A-Clark** [comment] 2023-06-07 17:01
@telusdcinco based on Steffi's comments above, it looks like past employees are showing up again in different parts of the platform. I thought this was fixed with ticket #888. Can you please work with Ji to fix? Thanks.

**Comment by jizhaogit** [comment] 2023-06-07 17:07
@Travis-A-Clark thanks for the clarification.  and one more question: for the shared with list and participant list, should we list those excused employees or should we roll back what i did about filter our the excused ones?

**Comment by Travis-A-Clark** [comment] 2023-06-07 17:17
@jizhaogit Past employees should be remove from everywhere except the Past Employees list and the Stats and Reporting > Employee Record. 

Excused employees should only be removed from the Goals Summary, Conversation Summary, and Shared Summary area of Stats and Reporting. They can still show up everywhere else.

I believe everything was working as expected before as we tested and approved ticket #888. This ticket #907 was only meant to remove Past Employees from those three areas: Stats and Reporting > Goal Summary, Conversation Summary, Shared Summary for both HR and Sys Admin. Seems like the work might have gone out of scope.

**Comment by Travis-A-Clark** [comment] 2023-06-07 17:27
As for Steffi's point #1 about who is listed as the current supervisor, we may need to chat as a team about this a bit further.

From my perspective, my understanding would be this:
1) Employee X reports to positon # 12345
2) The person in position # 12345 leaves the public service
3) The person in position # 12345 now has a date deleted or departure date or whatever Dennis is tracking, so they now move to the Past Employees list and are removed from the rest of the app as per ticket #888.
4) Position #12345 is now vacant. Either someone else moves into that position and becomes the new supervisor for Employee X, or position #12345 remains vacant and the PDP logic kicks in to skip that one vacant position and have Employee X report to whatever position number supervises position #12345. We have that skip one level when vacant logic already built in.

If all of that is true, than past employees cannot show up as a current supervisor. They can't be both the current supervisor and yet no longer an employee.

**Comment by Travis-A-Clark** [comment] 2023-06-08 17:10
@steffipravasi @jizhaogit 

Following the conversation this morning we agreed that:
- Past employees should not appear anywhere in the app except for Sys Admin > Employee List > Past Employees and Sys Admin > Stats and Reporting > Employee Record
- If a past employee is still showing up as the "Current Supervisor" for someone on their homepage, this is an issue with the data coming from PeopleSoft > ODS. We will need to speak with the PeopleSoft team to understand why there is a time lag between when an employee is deleted and when they are removed as the "Reports to" for others. The ODS issue will not be solved by this ticket.

**Comment by steffipravasi** [comment] 2023-06-09 19:50
@jizhaogit 
Test fail
Issue for past employees appearing as Current supervisor and in the participants list of conversations is still not resolved
![Screenshot 2023-06-09 at 3.47.36 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/5346a8d5-c791-4db3-bac1-4fc372462f0e)![Screenshot 2023-06-09 at 3.46.39 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/375f88f2-0ec2-434c-90a6-1f4e94fbd8a9)

Examples: Past employee - 002197 Levitt,Steve, Team member - Meijer,Maarty
Past employee - Jenkins,Dave, Team member - Howell,Ian
Test data: Past employee: Mortimer,Jeff D(Emp id:137586)
Team members: Struthers,Jordan can still see Jeff has his supervisor
Please refer to Travis' comment above to understand the expected behavior

**Comment by jizhaogit** [comment] 2023-06-09 21:21
@telusdcinco Hi Dennis, looks like we still have the lag between the "employee_demo.date_deleted" and "users.reportingto" data. in the cases that Setffi tested, team member can still see the past employees as their current supervisor.   I added a date_deleted null check for removing those past employees from the list but that will cause the "current supervisor" list be blank. We may need to check with ODS team to see how to solve this lag.  Thanks!

**Comment by jizhaogit** [comment] 2023-06-12 17:26
talked with Dennis, will setup a meeting with Justin (Justin Choy) to see what we can do from the ODS side to avoid this lag

**Comment by jizhaogit** [comment] 2023-06-13 13:46
have a meeting with Justin today.  there are 2 things update:
1.  we currently has one day behind of the ODS data refresh. should we increase this frequency?
2.  Justin needs to check with people soft side to get to know how often the people soft side updates the supervisor's data. if the lag cannot be fixed he will need to create a process so that the "current supervisor" can show the higher level's supervisor's data

**Comment by jizhaogit** [comment] 2023-06-13 20:13
just find a sample in the test:
employee "Levitt,Steve" is marked as past employee,  but there are still 4 users are reporting to him in test system:

![image.png](https://images.zenhubusercontent.com/620163b737f8d3386467e70d/e31b1416-7b8b-479d-b0c2-180122ae5548)

**Comment by jizhaogit** [comment] 2023-06-15 14:12
Justin provided some information:
1. ODS schedules data update for DEV at everyday 7:00 AM PCT.  PROD at everyday 9:00 AM PCT.
2. PeopleSoft update the level supervisor's information to the team members manually that cause the lag. Justin will contact PeopleSoft team to find out normally how long the lag will be. 
3. there is some more than 10 days update difference between ODS data and PDP side. sample as the following:

![image.png](https://images.zenhubusercontent.com/620163b737f8d3386467e70d/4b37f825-9474-44dd-8b0c-02a5ee6d9a6c)

![image.png](https://images.zenhubusercontent.com/620163b737f8d3386467e70d/dc9e1d40-841a-4c3c-90ac-2be783a45079)

In PDP side, the data of supervisor 067696 is updated at 2023-06-02. but in ODS,  067696 got updated at 2023-06-05.

**Comment by jessicahjwu** [comment] 2023-06-15 17:07
Marianne Tanti is on a TA and their supervisor in PeopleSoft was updated on Jun 8, 2023, in PS they are reporting to Janine Cox. However in the PDP it's still showing Marianne reporting to Sandra Winter, who is the skip-level supervisor for them:
![image.png](https://images.zenhubusercontent.com/641a1dcfdf400e29dabf707e/96534555-6483-4271-ab2b-de127a0c7742)
![image.png](https://images.zenhubusercontent.com/641a1dcfdf400e29dabf707e/0dabbea4-692a-48e4-b06b-fd47463bac6f)

Further info:
Janine Cox is currently on a TA as the Director of the team, in which their previous role was the Manager 
![image.png](https://images.zenhubusercontent.com/641a1dcfdf400e29dabf707e/277ffcf6-5afb-41d9-abc6-1c046f61fb64)
Janine's employee records in the PDP has been updated with her current TA position:
![image.png](https://images.zenhubusercontent.com/641a1dcfdf400e29dabf707e/edb7071d-6b83-410a-b360-afd8f586c8e3)

So the issue here is - TA position records are accurate, however the reporting relationship was not being picked up by the system

**Comment by jizhaogit** [comment] 2023-06-19 21:33
Jonathan suggested to use job data to instead of position data which will be more fit with PDP requirements.

**Comment by Travis-A-Clark** [comment] 2023-06-20 22:18
@telusdcinco @jizhaogit @steffipravasi @jessicahjwu I have moved all relevant info about incorrect or outdated supervisor information to ticket #1006. Let's continue the discussion about past employees and missed PeopleSoft updates there.

@steffipravasi please test this ticket only for its original purpose: removing past employees from the stats and reporting results (other than Sys Admin > Stats > Employee Record).

**Comment by steffipravasi** [comment] 2023-06-21 14:11
The original purpose of the ticket is achieved. Past employees removed from Statistics & Reports for Hr and Sys admin. 
Moving ticket for PO review.

**Closed** 2023-08-17 16:22 UTC
Labels: enhancement, PO Approved
