### ISSUE TITLE
My Conversations > Conversation Templates - Design 2.0 

### ISSUE THREAD

**Issue by jchow11** [bcgov/performance#777] opened 2022-09-09 21:02 UTC
**Description**
With new design for open conversations (ticket #736 and #623), "Suggested discussion questions" and "Preparing for the conversation" sections are represented in open conversations. Information is being displayed multiple times during the conversation template and open conversation stages. Let's reduce this redundant information and streamline the conversation templates section.

**Designs**
![My Conversations _ Conversation Templates Instructions expanded.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/cf2eea45-09c7-4909-b085-f27d55c97f9b)
![My Conversations _ Conversation Templates _ Other templates.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/cc6d191b-77d1-43ca-9c47-d14f095a997f)
![My Conversations _ Conversation Templates _ Other templates2.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/21b61187-6c41-4ad2-afbb-aa7ad92084b8)

**Comment by jchow11** [comment] 2022-09-09 21:06
**Description**
With new design for open conversations (ticket #736), "Suggested discussion questions" and "Preparing for the conversation" sections are represented in open conversations. Information is being displayed multiple times during the conversation template and open conversation stages. Let's reduce this redundant information and streamline the conversation templates section.

**Comment by Travis-A-Clark** [comment] 2022-09-22 00:06
@jchow11 Can we just add the participant drop down right into the conversation template list? So they select participants and hit "use this template" all from the main page rather than launching an additional modal?

**Comment by jchow11** [comment] 2022-09-22 05:16
@Travis-A-Clark  what do you think about this?
![My Conversations _ Conversation Templates _ Other templates.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/42f07c84-8258-4427-b1b8-0c257d390ec6)

**Comment by Travis-A-Clark** [comment] 2022-09-22 21:16
@jchow11 Yes, I think that's great. Do you mind just adding the view with the Performance Check-In template expanded and the new design and deleting unneeded stuff? Then I'll assign to Dev. Much appreciated.

**Comment by jchow11** [comment] 2022-09-26 17:15
@Travis-A-Clark done!

**Comment by Travis-A-Clark** [comment] 2022-09-26 22:46
@jchow11 I think we lost some of the screens! Was hoping to have the various views represented: Instructions expanded, Performance Check-In expanded, and Other Templates expanded. Apologies if I confused things!

**Comment by jchow11** [comment] 2022-09-27 14:37
@Travis-A-Clark Oh no that's my bad! Sorry about that. I've added them all back now.

**Comment by jizhaogit** [comment] 2023-04-10 17:38
@telusdcinco Please help do the code review. thanks!

**Comment by telusdcinco** [comment] 2023-04-10 17:54
@jizhaogit Looks good to migrate to Test.

**Comment by steffipravasi** [comment] 2023-04-11 21:06
1) The participant's list does not include the supervisor and the shared employee.
User: Cory Bargen
Supervisor: Katharine Lowther
Shared employee: Tracy Olsen
![Screenshot 2023-04-11 at 5.04.51 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/4508ffda-cc5a-45a4-9c80-e476602cc445)
2) Sort the participant's list in alphabetical order(a-Z)
![Screenshot 2023-04-11 at 5.04.51 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/0628e668-762a-4223-bb20-069c683c4376)

**Comment by jizhaogit** [comment] 2023-04-12 14:16
detected issues are addressed except #5.  the content is copied from the previous template. please confirm with @Travis-A-Clark if it needs update.

**Comment by steffipravasi** [comment] 2023-04-12 23:09
Note - Test user Cory Scott

**Comment by Travis-A-Clark** [comment] 2023-04-13 16:15
5. Please remove the additional text that says "Select at topic below to read more in the...."

Also, in the instructions text we need to change 

...hit "Use this template" to alert participants...
to
...hit "Start Conversation" to alert participants...

**Comment by Travis-A-Clark** [comment] 2023-04-13 17:26
Also just noticing that there is a difference in spacing and layout between the second and third sections. Performance Check-In Template section has a bigger gap between the header and the description and also has an extra row at the bottom even when the accordion is not expanded. Can we make this section look the same as the Other Templates section?

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/81ed1781-abe8-49f2-b553-1081257ed7b2)

**Comment by jizhaogit** [comment] 2023-04-13 18:36
the borderline is removed.  the gap should be the same the code of the two sessions are same

**Comment by steffipravasi** [comment] 2023-04-14 07:22
The Participants list does not display the supervisor/employee with whom the profile is shared with. 
User: Cory Scott
![Screenshot 2023-04-14 at 3.19.35 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/12eaccca-d5e0-4a45-8f6c-87b2b0467b42)![Screenshot 2023-04-14 at 3.19.21 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/bfec4a24-4e0a-4809-8215-ac58df0a299f)

**Comment by jizhaogit** [comment] 2023-04-14 12:53
shared manager list added back

**Comment by steffipravasi** [comment] 2023-04-14 18:12
I have one additional request. Can we align the Start conversation button to the drop-down?  It looks a little uneven right now. 
![Screenshot 2023-04-14 at 1.55.05 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/045f937b-40b9-4a13-a129-9ea1cd5a5d77)

**Comment by jizhaogit** [comment] 2023-04-17 12:42
@steffipravasi  all are done except the last request:   the "Particpants" label and the ddl is in the same table cell.  we cannot align the "start conversation" button in the center and still align with only one of them.    if we do need the items to be aligned all i will suggest moving the "Participants" label out to the column head like "when to use". please let me know what you think. thanks.

**Comment by steffipravasi** [comment] 2023-04-17 14:53
The UI changes requested are now fixed and looks good. 
![Screenshot 2023-04-17 at 10.51.38 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/8cc88a7e-e281-426a-9e09-91d0b8c1492c)
Ji to confirm with Travis if we can make the Participants title a common header.

**Comment by Travis-A-Clark** [comment] 2023-04-17 16:38
Yes, let's move Participants to title header. Thanks!

**Comment by steffipravasi** [comment] 2023-04-17 18:06
@jizhaogit assigning the ticket to you for the Participant title

**Comment by jizhaogit** [comment] 2023-04-18 18:19
participant title moved to column head

**Comment by steffipravasi** [comment] 2023-04-18 20:16
@jizhaogit The orange border is hidden on a smaller screen but displayed on a bigger screen
![Screenshot 2023-04-18 at 3.54.42 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/fe0e64ba-2ab7-4af8-aa20-5804bcff936c)
![Screenshot 2023-04-18 at 3.54.34 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/172e5e6f-65fe-4f4f-94be-6caa99423053)

**Comment by jizhaogit** [comment] 2023-04-19 13:06
@steffipravasi i verified from code level, didn't see any code that control the orange lane display behaviors. And i can't reproduce this issue.   

<table class="table table-striped">
                            <thead>
                                <tr style="border-bottom: solid #FCBA19">
                                    <th width="20%">Name</th>
                                    <th width="45%">When to use</th>
                                    <th width="15%">Participants</th>
                                    <th width="20%">&nbsp;</th>
                                </tr>
                            </thead>

style="border-bottom: solid #FCBA19"  is the orange line code.

**Comment by steffipravasi** [comment] 2023-04-19 16:22
Ji and I discussed the issue of the orange border missing and figured out that it remains hidden for both Performance Check-in and Other Templates sections. Also, the Issue occurs on Chrome and Edge only. Working fine on Safari and Firefox. However, the issue is only noticed on my 13" inch screen and is working fine on a 27" inch screen even on Chrome and Edge. Ji will be looking into the issue.

**Comment by jizhaogit** [comment] 2023-04-20 15:52
@steffipravasi as we discussed I added the orange line css in the <td> cell. please verify if this fix the issue.

**Comment by steffipravasi** [comment] 2023-04-20 17:51
Issue still persist in smaller screen. ![Screenshot 2023-04-20 at 1.51.03 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/e5372637-61ed-4953-be11-7ca9c11ae9f1)

**Comment by Travis-A-Clark** [comment] 2023-04-25 16:11
No need to fix this cosmetic issue at this time. We can move forward. Thanks!

**Comment by Travis-A-Clark** [comment] 2023-05-03 16:40
Two things:

- [ ] We seem to be missing the Participants header on the Performance Check-In list. Please add to make consistent with the Other Templates heading.

- [ ] When an employee selects a participant and clicks "Start Conversation" they are taken to the Open Conversation page, but all of the accordion headings remain closed and it's really hard to know what happened to the conversation you opened.

**Comment by steffipravasi** [comment] 2023-05-04 19:35
Participant's header added to both the sections
![Screenshot 2023-05-04 at 3.34.11 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/7fdb845b-d8b9-403d-8226-279fbdee0e70)
Moving ticket for PO review

**Closed** 2023-08-17 16:23 UTC
Labels: enhancement, PO Approved
