### ISSUE TITLE
ISSUE: Conversation due dates not reporting correctly when one conversation is closed and a new conversation is opened on the same day

### ISSUE THREAD

**Issue by Abuchana** [bcgov/performance#847] opened 2022-11-17 19:20 UTC
Incorrect date indicated for both users below: 

Hi Martha Wood,
Melissa Thickens would like to have a Performance Check-In conversation with you in the Performance Development Platform. Please work with Melissa Thickens to schedule a time in your Outlook calendar.
The deadline to complete your next performance conversation is **Oct 15, 2022**.
Thank you!
https://www.performance.gov.bc.ca

Hi there,
I went through my first round of performance conversations with my staff in mid October and I am already getting notifications that they are due for their next convos starting the first week of Dec.  Curious as to why this might be – wondering if they needed to sign off on the first round and didn’t, and if so, how/where might I verify/complete the sign offs in the application?

Much thanks,
Coreen Wolanski

**Comment by telusdcinco** [comment] 2022-11-17 20:57
This is possible timing issue with the sequence of events.  I can see backend from the conversations table that 3 conversations were created, and deleted/closed.
- Conversation ID 1411, created on Nov 15, deleted on Nov 16 
- Conversation ID 1499, created on Nov 16, deleted on Nov 16
- Conversation ID 1500, created on Nov 16, signed off on Nov 16 (closed within 15 minutes of creation)

**Comment by Abuchana** [comment] 2022-11-17 21:00
Ok, that makes sense then, it's a timing issue. I'm surprised this has not come up for a bunch of people...

**Comment by telusdcinco** [comment] 2022-11-18 00:06
Root Cause for the invalid due dates:
- The conversation-creation email notification is using the old function for generating the next conversation due date, which does not account for the Active/Classification/Manual Excuse criteria.
- This needs to be fixed in order to display the correct date.

Solution Concerns:
- The solution of switching over to the overnight calculated next conversation due date is not sufficient
- We have uncovered a scenario where is the next conversation due date will display the previous one, even though the supervisor/employee closed off the conversation  the same day that a new conversation is created.

Stop Gap:
- For the meantime, we have recommended to modify the email template for the notification of newly created conversations.  By removing the paragraph containing the next conversation due date, the email will be sent with  a generic content without the incorrect conversation due date.

Planned Implementation of Stop Gap:
- The template will be modified later tonight, and developer(s) will monitor the resulting email afterwards.
- The plan was approved by the SM on behalf of the PO.

Permanent Solution:
- We will have a deeper with the PO on the suggested permanent fix, or any alternate changes that needs to be included with the change.

fyi: @Abuchana , @jp-Telus

**Comment by jp-Telus** [comment] 2022-11-18 02:29
Per approval, the paragraph "The deadline to complete your next performance conversation is %4." was removed from the template called ADVICE_SCHEDULE_CONVERSATION.

![image.png](https://images.zenhubusercontent.com/60e73283e3a918390563e770/f5f7d856-3fd2-4df5-8c5b-1d6e2d38037f)

**Comment by jp-Telus** [comment] 2022-11-25 01:37
@Travis-A-Clark 

Upon to our discussion, the function call for getting the next conversation due date in the conversation model now using the data in the calculated from the daily process instead of real-time calculation. I did the migration and testing in both DEV and TEST regions. Here is the sample screenshot of the email

![image.png](https://images.zenhubusercontent.com/60e73283e3a918390563e770/03ea7b4f-c412-4e53-9bc5-3b04d02e3fdf)

Note for Production migration 
1. Update the notification template, add back the "The deadline to complete your next performance conversation is %4." was removed from the template called ADVICE_SCHEDULE_CONVERSATION.  

Thank you.

**Comment by steffipravasi** [comment] 2022-12-01 23:56
Test status: Pass
Performed the testing with James. The dates for conversations closed and opened of the same day remains the same.
User: Chad Hoskins, Rebecca Fontaine
-Created a new conversation - Goal Setting. The due date for it was 2023-03-18.
![Screen Shot 2022-12-01 at 6.53.34 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/50290b5d-74b4-43f6-8cdd-6f4e58eb1fcf)
- Closed the conversation by signing off from both the ends. 
- Created a new conversation - Goal Setting on the same day. The due date remained to 2023-03-18
![Screen Shot 2022-12-01 at 6.55.34 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/7b51e082-a3c1-4abc-9572-1fbb2fef011d)
Ready to be moved for PO review.

**Closed** 2022-12-15 21:47 UTC
Labels: bug, PO Approved
