### ISSUE TITLE
As an HR Admin, I want to see my employees in Statistics and Reporting as soon as I am assigned HR Admin access

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#809] opened 2022-10-03 21:23 UTC
A chron job was introduced to provide access for HR Admin to their assigned audience of employees (ticket #731). This is now in Production and is working as intended. It speeds up the load times, even for the Goal Summary page, significantly. However, it has introduced a new issue. If we assign HR Admin access to someone, they can go to the Statistics and Reporting area immediately, but they see all zero counts and no employees until the chron job runs at 1:30am the next morning.

Question: is there a way to trigger the command:BuildAdminOrgUsers when the HR Admin access is created rather than waiting until 1:30am?

**Comment by jp-Telus** [comment] 2023-03-14 14:59
To avoid the delay on HR admin to see the Statistic and Reporting when assign HR Admin access, the new logic are added :

1) when HR Admin assigned, the table admin_org_users will be populated for this HR admin at the same time. 
2) when HR Admin revoked, the table admin_org_users will be removed for this HR Amdin at the same time. 
3) when HR Admin change to administrator, the table admin_org_users will be removed at the same time. 
4) At the end of the date, the schedule cronjob will run for refresh the table admin_org_users for all HR Admin.

Status: WIP

**Comment by jp-Telus** [comment] 2023-03-24 15:27
The program was revised to use the new employee_demo_tree table and user_demo_jr_view view for immediately update HR Admin user access for Statistics and Reporting when changed. 

Based on my testing, to grant the "Justice" (contain over 8725 employee) to HR admin, it took 10 secs to update on my local,  and only 8705 employees found for Justice, due to no level 5 stored in this Access and Permission data. 

Status: Pushed to DEV region for dev testing.

**Comment by steffipravasi** [comment] 2023-03-29 23:17
@telusdcinco The Organization field is not loading any organizations in the dropdown list. ![Screenshot 2023-03-29 at 7.15.17 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/0bce52c1-2e59-4d0a-aa96-f639827aa9aa)

**Comment by steffipravasi** [comment] 2023-03-30 01:12
Test Failed
Tried selecting one organization and then selecting other organization, but access is assigned to the first selected organization. 
Steps to reproduce:
I) Select user, add reason for assigning
ii) Select organization: Agriculture and Food
iii) Click Filter
iv) Select the whole tree for Agriculture and Food
v) Select organization: BC Pension Corp
vi) Click Filter
vii) Select the whole tree for BC Pension Corp
viii) Hit the Assign Employees
Expected result: Employee should be assigned BC Pension Corp organization 
Actual result: Employee assigned Agriculture and Food
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/809.mov?csf=1&web=1&e=cjbd7P

**Comment by telusdcinco** [comment] 2023-03-30 14:33
@steffipravasi 
Please retry the scenario again.

**Comment by steffipravasi** [comment] 2023-04-03 16:30
Ticket validated. 
Moving for PO review.

**Comment by Travis-A-Clark** [comment] 2023-04-24 19:27
@telusdcinco Trying to validate this ticket. When to Sys Admin > Access and Permissions. Page was very slow to load. I was able to complete steps 1 and 2 on the page, but when I try to select a business unit in step 3, it just spins and I receive an error message.
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/da557100-7689-487f-b79c-92a29180e62d)

**Comment by telusdcinco** [comment] 2023-04-27 20:58
@Travis-A-Clark Fixed the error above.

**Comment by steffipravasi** [comment] 2023-04-28 15:53
The errors faced while creating Access is fixed.

**Comment by steffipravasi** [comment] 2023-05-15 13:48
@telusdcinco 
Assigning HR access to an employee is not completely successful and the org does not appear in the drop-down list for Statistics & Reporting which results in all the numbers mismatching the Sys admin
Test case: Assigned user 000318	Harlow,J. Robert	Bob.Harlow@gov.bc.ca HR access to Justice org
![Screenshot 2023-05-15 at 9.48.02 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/4a8127eb-7894-4add-b613-d0a86d30764d)

**Comment by telusdcinco** [comment] 2023-05-16 19:13
@steffipravasi The org dropdowns for HR Admin as been fixed and is loading normally.

**Comment by steffipravasi** [comment] 2023-05-16 20:02
@telusdcinco I assigned HR access to an employee, but still can't see the org in Statistics & Reporting
![Screenshot 2023-05-16 at 4.01.22 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/1b4a4f49-22bb-4965-82a2-bfa908b79128)

**Comment by telusdcinco** [comment] 2023-05-16 21:10
@steffipravasi Pushed the changes to store thee grants to the new tables to Test, which drives the org dropdown list for HR Admins.

**Comment by steffipravasi** [comment] 2023-05-17 04:21
@telusdcinco 
Unfortunately for some orgs I still see some differences:
1) Citizen Services
![Screenshot 2023-05-17 at 12.02.15 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/b0159011-bc16-4342-9411-c27fbed778f9)
2) BC PSA 
![Screenshot 2023-05-16 at 11.15.41 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/dab7770c-e9e4-4c30-b527-dc15aa3000cc)
3) Community Living BC 
![Screenshot 2023-05-16 at 11.32.16 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/25776e27-b0d5-4560-9283-f273aac288ee)
4) Finance
![Screenshot 2023-05-17 at 12.21.11 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/5c6a1adf-c4a8-4395-aa8b-b2cd909312d9)

**Comment by steffipravasi** [comment] 2023-05-17 21:54
Assigning HR access and permission to users and the numbers mismatching issue is fixed.

**Comment by Travis-A-Clark** [comment] 2023-05-24 18:14
@steffipravasi With user Jessica Wu in TEST I set her up with HR Admin access to all of Public Service Agency and Service BC (which is a level 1 business unit under the Citizen's Services org). The result is that only Public Service Agency shows up under the Organization dropdown, even though the user has access to parts of two different organizations. It makes it really tough to filter results on all the HR Admin issues. 

Is it possible to list all orgs in the Organization dropdown even if the user only has access to sub-levels of that org?

**Comment by telusdcinco** [comment] 2023-05-24 20:58
@Travis-A-Clark  
The dropdown list has been fixed in Test.

**Comment by steffipravasi** [comment] 2023-05-25 05:57
Issue addressed and validated on test.
![Screenshot 2023-05-25 at 1.56.53 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/13953103-8ca7-4c2a-bcce-76e578aa67dc)![Screenshot 2023-05-25 at 1.56.58 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/505303f3-5a25-4d16-aa95-a37c32d79268)

**Closed** 2023-08-17 16:22 UTC
Labels: enhancement, PO Approved
