### ISSUE TITLE
Updates to Org Hierarchy: inherited permissions

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#785] opened 2022-09-16 00:37 UTC
Scenario:

1) An organization has 396 business units in it. A goal is pushed out to the goal bank for the organization. Two weeks later, the organization now has 402 business units in it. The goal is not reflected in any of the new business units even though it was meant for the entire organization.

2) HR Admin access is granted to a user for an organization that has 396 business units. Two weeks later, the organization has 402 business units. The HR Admin does not have access to the new business units and has no way of knowing they exist.

Potential solution:

- Copy the concept of inherited permissions that Windows uses for folders (parent, child, etc.) so that changes are automatically captured
- Run a daily report of changes (Deltas) in org hierarchy data coming in from ODS and manually update required permissions and goals

Can also work with Steven Jones (PSA), Patrick (Telus) on potential solutions as needed.

**Comment by telusdcinco** [comment] 2023-03-06 16:40
Related changes being applied for #796.

**Comment by telusdcinco** [comment] 2023-04-04 12:53
@jizhaogit Please review changes for #785.

**Comment by jizhaogit** [comment] 2023-04-04 13:00
@telusdcinco is good for me. please go ahead and do your migrate. thanks!

**Comment by steffipravasi** [comment] 2023-05-11 16:17
Discussed some issues with Access & Permissions for orgs with Dennis. 
Discrepancies marked in red in the attachment to track: https://bcgov.sharepoint.com/:x:/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/HRaccess%20%23%20785.xlsx?d=w52d5849e1b364452aa1fd1f0db68053a&csf=1&web=1&e=H2u9Re

**Comment by steffipravasi** [comment] 2023-05-17 20:20
@telusdcinco Adding the issue we talked about 
When assigning access, if the Static and Inherited checkboxes are checked, the inheritance column in manage existing access displays 'No' instead of yes
![Screenshot 2023-05-17 at 4.18.45 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/20b53300-ce4a-417a-b9e6-e7aebb36281a) ![Screenshot 2023-05-17 at 4.19.07 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/d4d2f8f9-3a24-4cf1-b640-70c02dd1382f)

**Comment by steffipravasi** [comment] 2023-05-17 20:42
Assigning HR access to a user also assigns few users who do not belong to that org. 
For eg: Assigned Justice org to James Whissell. I can see 6 extra users who do not belong to Justice
![Screenshot 2023-05-17 at 4.41.54 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/bb6b5cde-202a-455d-8adc-644676496d1d)![Screenshot 2023-05-17 at 4.42.06 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/835cbac6-1b4f-4b9a-a5c0-b15b3a558762)

**Comment by steffipravasi** [comment] 2023-06-15 00:57
1) Created a new access to a user with Static and Inherited permission, but the Manage Existing Access displays 'No' for inheritance
![Screenshot 2023-06-14 at 8.47.05 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/d8a55c0e-0e00-4713-99ab-c5139a7ce8db)
User: 194946	Jones,Trystan
Org: Municipal Affairs

**Comment by steffipravasi** [comment] 2023-06-16 19:00
Confirming that the reported issue is working as expected and is not an issue. The most high level org remains inherited and the sub-levels are displayed as not inherited but are actually inherited by the main org. 
Moving ticket for PO review.

**Comment by Travis-A-Clark** [comment] 2023-06-19 22:30
@steffipravasi Is this a known issue? Apologies if it was already discussed.

When I select "inherited" when assigning a goal, I get the message below. Do I have to select static and inherited for it to work?

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/5a497c4f-d796-4cdf-95da-9dc8fcc04a9b)

**Comment by telusdcinco** [comment] 2023-06-26 16:54
2 items fixed.
- Inherited selections are now saved in Sys/HR Admin Goal Bank.
- Sys/HR Admin Goal Bank save confirmation now also checks for inherited audience.  "Are you sure you want to create the goal without an audience?" will only show up when there is no selected Static/Inherited checkbox.

**Comment by steffipravasi** [comment] 2023-06-26 22:29
@telusdcinco Not sure if this issue is caused by the SR role ticket, but the org drop-down list in Goal Bank does not load for Sys Admin![Screenshot 2023-06-26 at 6.26.37 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/7c3d2966-6977-40ef-9cc5-6d1fafeafc7a)

**Comment by steffipravasi** [comment] 2023-06-26 23:32
@telusdcinco 
Able to reproduce issue number 3. Please refer to the recording.
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/Screen%20Recording%202023-06-26%20at%207.29.12%20PM.mov?csf=1&web=1&e=bCVd9j

**Comment by telusdcinco** [comment] 2023-06-27 01:04
@steffipravasi 
Item 1 was due to #942 changes to fix security changes.  Pushed the fix under #942 ticket.
Item 2 was to include the inherited orgs in the notifications.  Pushed the fix under #975 ticket.
Item 3 was due to #620 changes for Goal Bank 2.0.  Pushed the fix under #620 ticket.

**Comment by steffipravasi** [comment] 2023-06-27 03:36
@telusdcinco 
Issue number 2 is not fixed. 
Not receiving notifications for email and in-app for any of the 2 checkboxes feature:
- Static only
- Static and Inherited
- Inherited only

**Comment by telusdcinco** [comment] 2023-06-27 16:13
@steffipravasi 
Fixed Item 2.
Fixed issue in modal confirmation, submit button remains disabled when cancel button is clicked.

Pushing to Test

**Comment by steffipravasi** [comment] 2023-06-27 17:23
Issue resolved and validated. 
Inherited only assigns the goal to entire org (BU displayed as one only). 
Moving for PO review.

**Closed** 2023-08-17 16:22 UTC
Labels: bug, enhancement, PO Approved
